# Basic
title: 高傲的电工李
subtitle: 个人博客
description: 欢迎来到我的个人博客
# 头像里面的标题
avatarTitle: 李文博
# 头像里面的描述
avatarDesc: 机电 / 机器学习
url: "https://wenboli-cn-de.github.io"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
#comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    # disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    # weibo: 5366874726 
     github: WenboLi-CN-DE
    # zhihu: panpanleopard
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter: 
     mail: lwb_010@163.com

permalink: /:year/:month/:categories/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'} 
 #   - {title: 分类, description: categories, url: '/categories'}    
    - {title: 标签, description: tags, url: '/tags'}         
    - {title: 关于我, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"

# MathJax rendering for layout:page (e.g. post preview)
# page-mathjax: true
# 说明：是否对数学公式进行渲染（渲染的话显示的公式在网页加载的时候会出现变化）


markdown: kramdown

